name: Generate Debug Apk

on:
  push:
    branches:
      - master


jobs:
  build_apk:
    name: Build Apk
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/**.apk




