name: Firebase Distribution

on:
  workflow_run:
    workflows:
      - "Generate Debug Apk"
    types:
      - completed

jobs:

  download_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-debug.apk
          github-token: ${{ github.token }}
          run-id: 10248960077

      - name: Print artifacts files
        run: ls -R artifacts
      - name: Print artifacts files path
        run: cd artifacts


  deploy:

    runs-on: ubuntu-latest
    needs: [download_artifact]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      #      - name: build release
      #        run: ./gradlew assembleRelease
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          #          groups: testers
          file: app-debug.apk
