name: Firebase Distribution

on:
  workflow_run:
    workflows:
      - "Generate Debug Apk"
  #    types:
  #      - completed

  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'
jobs:

  #  download_artifact:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Download Artifact
  #        uses: actions/download-artifact@v4
  #        with:
  #          name: app-debug.apk
  #          path: artifacts
  #          github-token: ${{ github.token }}
  #          run-id: 10248960077
  #
  #      - name: Print artifacts files
  #        run: ls -R artifacts
  #      - name: Print artifacts files path
  #        run: ls -d -1 $PWD/**/*

  #  build_apk:
  #    name: Build Apk
  #    runs-on: ubuntu-latest
  #    continue-on-error: true
  #
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v4.1.7
  #
  #      - name: Setup Java
  #        uses: actions/setup-java@v4.2.1
  #        with:
  #          java-version: 17
  #          distribution: 'temurin'
  #
  #      - name: Change wrapper permissions
  #        run: chmod +x ./gradlew
  #
  #      - name: Build Gradle
  #        run: ./gradlew assembleDebug


  deploy:

    runs-on: ubuntu-latest
    #    needs: [download_artifact]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      #      - name: Change wrapper permissions
      #        run: chmod +x ./gradlew
      #
      #      - name: Build Gradle
      #        run: ./gradlew assembleDebug

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-debug.apk
          path: artifacts
          github-token: ${{ github.token }}
          run-id: 10248960077

      - name: Print artifacts files
        run: ls -R artifacts
      - name: Print artifacts files path
        run: ls -d -1 $PWD/**/*


      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          #          groups: testers
          file: artifacts/app-debug.apk
          debug: true
          releaseNotes: ${{ inputs.release_notes }}
