name: Firebase Distribution

on:
  workflow_run:
    workflows:
      - "Generate Debug Apk"
    types:
      - completed

  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: app-debug22.apk
          path: artifacts
          github-token: ${{ github.token }}

      - name: Print artifacts files
        run: ls -R artifacts
      - name: Print artifacts files path
        run: ls -d -1 $PWD/**/*

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          #          groups: testers
          file: artifacts/app-debug22.apk
          debug: true
          releaseNotes: ${{ inputs.release_notes }}